
modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory
license="LGPL-2.1 license"
issueTrackerURL="https://github.com/Ddasb/MagicAnthropie/issues" #optional

[[mods]] #mandatory
modId="magicanthropie" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Magic Anthropie" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/Ddasb/MagicAnthropie" #optional
logoFile="examplemod.png" #optional
credits="Kiuseii" #optional
authors="Kiuseii" #optional
description='Some description'

[[dependencies.magicanthropie]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.magicanthropie]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
